name: zombies_game
description: "A new Flutter project."
publish_to: "none"
version: 0.1.5+4

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.8.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  intl: ^0.20.2
  url_launcher: ^6.2.4
  share_plus: ^11.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  collection: ^1.18.0
  shared_preferences: ^2.3.2
  flutter_bloc: ^9.1.1
  audioplayers: ^6.1.0
  provider: ^6.1.2
  easy_localization: ^3.0.8
  flutter_yandex_games: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.1
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter_native_splash:
  background_image: "assets/images/splatfd.png"
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/audio/
    - assets/icons/
    - assets/images/
    - assets/translations/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat-Italic-VariableFont_wght.ttf
          style: italic
